# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Start CPU&Memory Monitor
  hosts: elect_servers
  become: yes
  become_user: elect
  gather_facts: false
  tasks:
    - name: CPU&Memory Monitor
      shell: |
        . /etc/profile &&
        nohup bash /home/elect/ELECTExp/scripts/status/stats.sh {{ expName }} {{ stage }} > /home/elect/run.log 2>&1 &
      vars:
        expName: "Exp#1479-Load-Cassandra-DATAPATH"
        stage: "Compaction"
      register: command_result
      ignore_errors: true
    - name: Fail the play if the previous command did not succeed
      fail: msg="the command failed"
      when: "'FAILED' in command_result.stderr"

- name: Monitor before flush
  hosts: elect_servers
  become: yes
  become_user: elect
  tasks:
    - name: Monitor
      shell: |
        . /etc/profile && bash /home/elect/ELECTExp/scripts/status/stateCapture.sh {{ expName }} {{ workload }} {{ stage }}
      vars:
        expName: "Exp#1479-Load-Cassandra-DATAPATH"
        workload: "workload_template"
        stage: "Before-flush-compaction"
      register: command_result
      ignore_errors: true
    - name: Fail the play if the previous command did not succeed
      fail: msg="the command failed"
      when: "'FAILED' in command_result.stderr"

- name: Force flush and compaction
  hosts: elect_servers
  become: yes
  become_user: elect
  tasks:
    - name: Force flush
      shell: |
        . /etc/profile && cd /mnt/ssd/CassandraEC && bin/nodetool flush
      register: command_result
      ignore_errors: true
    - name: Fail the play if the previous command did not succeed
      fail: msg="the command failed"
      when: "'FAILED' in command_result.stderr"
    - name: Wait until compaction is done
      pause:
        seconds: 21600

- name: Stop CPU&Memory Monitor
  hosts: elect_servers
  become: yes
  become_user: elect
  gather_facts: false
  tasks:
    - name: CPU&Memory Monitor
      shell: |
        . /etc/profile && bash /home/elect/ELECTExp/scripts/status/killMonitor.sh
      register: command_result
      ignore_errors: true

- name: Monitor after flush
  hosts: elect_servers
  become: yes
  become_user: elect
  tasks:
    - name: Monitor
      shell: |
        . /etc/profile && bash /home/elect/ELECTExp/scripts/status/stateCapture.sh {{ expName }} {{ workload }} {{ stage }}
      vars:
        expName: "Exp#1479-Load-Cassandra-DATAPATH"
        workload: "workload_template"
        stage: "After-flush-compaction"
      register: command_result
      ignore_errors: true
    - name: Fail the play if the previous command did not succeed
      fail: msg="the command failed"
      when: "'FAILED' in command_result.stderr"

