---
- name: Rebuild and start OSS file server
  hosts: elect_oss
  become: yes
  become_user: elect
  tasks:
    - name: Execute script start-server.sh
      shell: |
        . /etc/profile &&
        bash PATH_TO_SCRIPTS/Run/start-server.sh {{ maxLevel }} {{ initialDelay }} {{ concurrentEC }} {{ target_saving }} {{ data_block_num }} {{ parity_block_num }} {{ mode }}
      vars:
        maxLevel: 9
        initialDelay:  65536
        concurrentEC: 64
        target_saving: 0.6
        data_block_num: 4
        parity_block_num: 2
        mode: "raw"
      register: command_result
      ignore_errors: True
    - name: Fail the play if the previous command did not succeed
      fail: msg="the command failed"
      when: "'FAILED' in command_result.stderr"
    - name: Wait until all nodes are ready
      pause:
        seconds: 90

- name: Rebuild and start Cassandra servers
  hosts: elect_servers
  become: yes
  become_user: elect
  tasks:
    - name: Execute script start-server.sh
      shell: |
        . /etc/profile &&
        bash PATH_TO_SCRIPTS/Run/start-server.sh {{ maxLevel }} {{ initialDelay }} {{ concurrentEC }} {{ target_saving }} {{ data_block_num }} {{ parity_block_num }} {{ mode }}
      vars:
        maxLevel: 9
        initialDelay:  65536
        concurrentEC: 64
        target_saving: 0.6
        data_block_num: 4
        parity_block_num: 2
        mode: "raw"
      register: command_result
      ignore_errors: True
    - name: Fail the play if the previous command did not succeed
      fail: msg="the command failed"
      when: "'FAILED' in command_result.stderr"
    - name: Wait until all nodes are ready
      pause:
        seconds: 90

- name: Setup log levels
  hosts: elect_servers
  become: yes
  become_user: elect
  tasks:
    - name: Setup log levels
      shell: |
        . /etc/profile && cd PATH_TO_PROTOTYPE && bin/nodetool setlogginglevel org.apache.cassandra error && bin/nodetool setlogginglevel ROOT error
      register: command_result
      ignore_errors: true

- name: Prepare keyspace and tables for loading
  hosts: elect_client
  become: yes
  become_user: elect
  tasks:
    - name: Execute script start-client.sh
      command: bash PATH_TO_SCRIPTS/Run/start-client.sh {{ coordinator }} {{ sstable_size_in_mb }} {{ fanout_size }} {{ mode }}
      vars:
        coordinator: "172.27.96.1"
        sstable_size_in_mb: 4
        fanout_size: 10
        mode: "raw"
      register: command_result
      ignore_errors: True
    - name: Fail the play if the previous command did not succeed
      fail: msg="the command failed"
      when: "'FAILED' in command_result.stderr"

- name: Start CPU&Memory Monitor
  hosts: elect_servers
  become: yes
  become_user: elect
  gather_facts: false
  tasks:
    - name: CPU&Memory Monitor
      shell: |
        . /etc/profile &&
        nohup bash PATH_TO_SCRIPTS/status/stats.sh {{ expName }} {{ stage }} > /home/elect/run.log 2>&1 &
      vars:
        expName: "SampleExpName"
        stage: "Loading"
      register: command_result
      ignore_errors: true
    - name: Fail the play if the previous command did not succeed
      fail: msg="the command failed"
      when: "'FAILED' in command_result.stderr"

- name: Monitor before loading
  hosts: elect_servers
  become: yes
  become_user: elect
  tasks:
    - name: Monitor
      shell: |
        . /etc/profile && bash PATH_TO_SCRIPTS/status/stateCapture.sh {{ expName }} {{ workload }} {{ stage }}
      vars:
        expName: "SampleExpName"
        workload: "workload_template"
        stage: "Before-loading"
      register: command_result
      ignore_errors: true
    - name: Fail the play if the previous command did not succeed
      fail: msg="the command failed"
      when: "'FAILED' in command_result.stderr"

- name: Load data
  hosts: elect_client
  become: yes
  become_user: elect
  tasks:
    - name: Execute script loadDB.sh
      command: bash PATH_TO_SCRIPTS/Run/loadDB.sh {{ record_count }} {{ key_length }} {{ filed_length }} {{ threads }} {{ workload }} {{ expName }} {{ keyspace }} {{ trace }}
      vars:
        record_count: 100000000
        key_length: 24
        filed_length: 1000
        threads: 64
        workload: "workloads/workload_template"
        expName: "SampleExpName"
        keyspace: "ycsb"
        trace: "off"
      register: command_result
      ignore_errors: True
    - name: Fail the play if the previous command did not succeed
      fail: msg="the command failed"
      when: "'FAILED' in command_result.stderr"
    - name: Wait until insertion is done
      pause:
        seconds: 5

- name: Monitor after loading
  hosts: elect_servers
  become: yes
  become_user: elect
  tasks:
    - name: Monitor
      shell: |
        . /etc/profile && bash PATH_TO_SCRIPTS/status/stateCapture.sh {{ expName }} {{ workload }} {{ stage }}
      vars:
        expName: "SampleExpName"
        workload: "workload_template"
        stage: "After-Loading"
      register: command_result
      ignore_errors: true
    - name: Fail the play if the previous command did not succeed
      fail: msg="the command failed"
      when: "'FAILED' in command_result.stderr"

- name: Stop CPU&Memory Monitor
  hosts: elect_servers
  become: yes
  become_user: elect
  gather_facts: false
  tasks:
    - name: CPU&Memory Monitor
      shell: |
        . /etc/profile && bash PATH_TO_SCRIPTS/status/killMonitor.sh
      register: command_result
      ignore_errors: true

- name: Backup Logs
  hosts: elect_servers
  become: yes
  become_user: elect
  tasks:
    - name: copy logs
      command: bash PATH_TO_SCRIPTS/Run/copyLogs.sh {{ record_count }} {{ operation_count }} {{ threads }} {{ workload }} {{ expName }} {{ keyspace }}
      vars:
        record_count: 10000000
        operation_count: 10000000
        threads: 64
        workload: "workload_template"
        expName: "Exp#1-Normal-Run-Cassandra-DATAPATH"
        keyspace: "ycsb"
      register: command_result
      ignore_errors: true
    - name: Fail the play if the previous command did not succeed
      fail: msg="the command failed"
      when: "'FAILED' in command_result.stderr"