---
- name: Rebuild and start Cassandra servers
  hosts: cassandra_servers

  tasks:
  - name: Execute script start-server.sh
    command: sh /mnt/ssd/Debug/CassandraEC/scripts/start-server.sh
    register: command_result
    ignore_errors: True

  - name: Fail the play if the previous command did not succeed
    fail: msg="the command failed"
    when: "'FAILED' in command_result.stdeer"

  - name: Pause for 20 seconds
    pause:
      seconds: 20

- name: Prepare keyspace and tables for evaluation
  hosts: cassandra_client

  tasks:
  - name: Execute script start-client.sh
    command: sh /mnt/ssd/Debug/CassandraEC/scripts/start-client.sh {{ inventory_hostname }} 4 4 # <coordinator address>, <sstable size in MB>, <fanout size>
    register: command_result
    ignore_errors: True

  - name: Fail the play if the previous command did not succeed
    fail: msg="the command failed"
    when: "'FAILED' in command_result.stdeer"

  - name: Pause for 10 seconds
    pause:
      seconds: 10

- name: Start a evaluation
  hosts: cassandra_client

  tasks:
  - name: Execute script start-eveluation.sh
    command: sh /mnt/ssd/Debug/CassandraEC/scripts/start-evaluation.sh {{ inventory_hostname }} # <coordinator address>
    register: command_result
    ignore_errors: True

  - name: Fail the play if the previous command did not succeed
    fail: msg="the command failed"
    when: "'FAILED' in command_result.stdeer"